server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态爱创建路由的功能，利用微服务名称进行路由
      routes:
        - id: payment_route #路由的id
#          uri: http://localhost:8001
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/get/** # 断言，路径相匹配的进行路由
#            - After=2021-03-08T21:43:15.681+08:00[Asia/Shanghai]
#            - Between=2021-03-08T21:43:15.681+08:00[Asia/Shanghai],2021-03-08T22:43:15.681+08:00[Asia/Shanghai]

        - id: payment_route2 #路由的id
#          uri: http://localhost:8001
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/lb #断言,路径相匹配的进行路由
#            - After=2021-03-08T21:43:15.681+08:00[Asia/Shanghai]
#            - Before=2021-03-08T22:43:15.681+08:00[Asia/Shanghai]
#            - Cookie=username,taylor
#            - Header=X-Request-Id, \d+ #请求头要有X-Request-Id属性，并且值为正数
#            - Host=**.**.com
#            - Method=GET
#            - Query=username, \d+ # 要有参数名username并且值还要是正整数才能路由
#             过滤
#            filters:
#              - AddRequestHeader=X-Request-red, blue

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/